### ISSUE TITLE
Where can i find a Windows installer?

### ISSUE THREAD

**Issue by mehdadoo** [tuarua/AIR-Tools#6]
In the release folder, there is a max installer for air-tools. [ air-tools-macos-installer-x64-1.4.0.pkg ]
However i can not find a windows installer.

How can i install air-tools on windows machine?
[air-tools seems necessary to use AdMob ANE]

Thank you for your open source softwares.

**Comment by tuarua** [comment]
It's under releases. 1.3.0 was the last version for Windows, should probably upload it to 1.4.0 for visibility.
https://github.com/tuarua/AIR-Tools/releases/tag/1.3.0

N.B. AdMobANE is a bit out of date now, so may not work with with AIR 50
